name: build-action
on: push
jobs:
  build_docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          use-ros2-testing: true
          required-ros-distributions: humble
      - name: build workspace
        uses: ros-tooling/setup-ros@v0.7
        with:
          path: src/github-action-learning
      - run: echo "hello world"
      - run: . /opt/ros/humble/setup.sh && colcon build
