name: build-action
on: push
jobs:
  build_docker:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble iron
      - run: "source /opt/ros/humble/setup.bash && ros2 run --help"
      - run: "source /opt/ros/iron/setup.bash && rosnode --help"
